Farmacia.Web/Models/ErrorViewModel.cs
namespace Farmacia.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Farmacia.Web/ViewModels/FabNumberVM.cs
using Farmacia.Domain.Entities;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Farmacia.Web.ViewModels
{
    public class FabNumberVM
    {
        public Fabricas Fabricas_Number { get; set; } = null!;

        [ValidateNever]
        public IEnumerable<SelectListItem>? FabList { get; set; }
    }
}

Farmacia.Web/Controllers/FabricaController.cs
using Farmacia.Application.Common.Interfaces;
using Farmacia.Domain.Entities;
using Farmacia.Infrastructure.Data;
using Farmacia.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Farmacia.Web.Controllers
{
    public class FabricaController : Controller
    {
        private readonly IUnityOfWork _unityOfWork;

        public FabricaController(IUnityOfWork unityOfWork)
        {
            _unityOfWork = unityOfWork;
        }

        public IActionResult Index()
        {
            var fabNumbers = _unityOfWork.Fabricas
                .GetAll(includeProperties: "Medicamentos");
            return View(fabNumbers);
        }

        public IActionResult Create()
        {
            FabNumberVM fabNumberVM = new FabNumberVM
            {
                FabList = _unityOfWork.Medicamentos.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(fabNumberVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FabNumberVM obj)
        {
            bool medexists = _unityOfWork.Fabricas.Any(u => u.Id == obj.Fabricas_Number.Id);
            if (ModelState.IsValid && !medexists)
            {
                _unityOfWork.Fabricas.Add(obj.Fabricas_Number);
                _unityOfWork.Save();
                TempData["success"] = "The fabric has been created successfully";
                return RedirectToAction(nameof(Index));
            }
            if (medexists)
            {
                TempData["error"] = "The Medicine Number already exists";
            }
            obj.FabList = _unityOfWork.Medicamentos.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }




        public IActionResult Update(int farmId)
        {
            FabNumberVM fabNumberVM = new FabNumberVM
            {
                FabList = _unityOfWork.Medicamentos.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Fabricas_Number= _unityOfWork.Fabricas.Get(_=> _.Id == farmId)
                
            };
            if(fabNumberVM.Fabricas_Number is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(fabNumberVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Fabricas obj)
        {
            if(ModelState.IsValid)
            {
                _unityOfWork.Fabricas.Update(obj);
                _unityOfWork.Save();
                TempData["success"] = "The Fabric has been updated sucessfull";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The Fabric has been not updated sucessfull";
            return View(obj);
        }
        public IActionResult Delete(int farmId)
        {
            FabNumberVM fabNumberVM = new()
            {
                FabList = _unityOfWork.Medicamentos.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Fabricas_Number = _unityOfWork.Fabricas.Get(_ => _.Id == farmId)
            };

            if (fabNumberVM.Fabricas_Number is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(fabNumberVM);
        }
        [HttpPost]
        public IActionResult Delete(FabNumberVM fabNumberVM)
        {
            Fabricas? objFromDb = _unityOfWork.Fabricas.Get(_=> _.Id == fabNumberVM.Fabricas_Number.Id);
            if (objFromDb is not null)
            {
                _unityOfWork.Fabricas.Remove(objFromDb);
                _unityOfWork.Save();
                TempData["success"] = "The Fabric number has been deleted successfully.";

                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The fabric  could not be deleted.";
            return View(fabNumberVM);
        }
    }
}

Farmacia.Web/Controllers/HomeController.cs
using Farmacia.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Farmacia.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Farmacia.Web/Views/Fabrica/Create.cshtml
@model FabNumberVM
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create a Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="form-floating py-2 col-12">
                <div class="form-floating py-1 col-12">
                    <input asp-for="Fabricas.Name" class="form-control border shadow" />
                    <label asp-for="Fabricas.Name" class="ms-2"></label>
                    <span asp-validation-for="Fabricas.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Fabricas.Medicamentos_Id" asp-items="@Model.FabList"
                            class="form-select border shadow">
                        <option disabled selected> --Select a Fabric--</option>
                    </select>
                    <label asp-for="Fabricas!.Medicamentos_Id" class="ms-2"></label>
                    <span asp-validation-for="Fabricas!.Medicamentos_Id!" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Fabricas.Local" class="form-control border shadow" />
                    <label asp-for="Fabricas.Local" class="ms-2"></label>
                    <span asp-validation-for="Fabricas.Local" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i>
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Farmacia.Web/Views/Fabrica/Delete.cshtml
@model Farmacia.Web.ViewModels.FabNumberVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete a Fabric</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="form-floating py-2 col-12">
                <div class="form-floating py-1 col-12">
                    <input asp-for="Fabricas_Number.Name" class="form-control border shadow" />
                    <label asp-for="Fabricas_Number.Name" class="ms-2"></label>
                    <span asp-validation-for="Fabricas_Number.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Fabricas_Number.Medicamentos_Id" asp-items="Model.FabList" class="form-select border shadow">
                        <option disabled selected> --Select a Medicamento--</option>
                    </select>
                    <label asp-for="Fabricas_Number.Medicamentos_Id" class="ms-2"></label>
                    <span asp-validation-for="Fabricas_Number.Medicamentos_Id" class="text-danger"></span>
                </div>
                <input asp-for="Fabricas_Number.Id" hidden />
                <div class="form-floating py-2 col-12">
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Fabricas_Number.Id" class="form-control border shadow" />
                        <label asp-for="Fabricas_Number.Id" class="ms-2"></label>
                        <span asp-validation-for="Fabricas_Number.Id" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Fabricas_Number.Local" class="form-control border shadow" />
                        <label asp-for="Fabricas_Number.Local" class="ms-2"></label>
                        <span asp-validation-for="Fabricas_Number.Local" class="text-danger"></span>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-trash-circle"></i>Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Farmacia.Web/Views/Fabrica/Index.cshtml
@model IEnumerable<Fabricas>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-0">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Medicines List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Fabrica" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create a Fabric
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Medicamentos ID</th>
                    <th>Local</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Id</td>
                        <td>@obj.Name</td>
                        <td>@obj.Medicamentos.Name</td>
                        <td>@obj.Local</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-action="Update" asp-route-farmId="@obj.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-action="Delete" asp-route-farmId="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Farmacia.Web/Views/Fabrica/Update.cshtml
@model FabNumberVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update a Fabric</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="form-floating py-2 col-12">
                <div class="form-floating py-1 col-12">
                    <input asp-for="Fabricas_Number.Name" class="form-control border shadow" />
                    <label asp-for="Fabricas_Number.Name" class="ms-2"></label>
                    <span asp-validation-for="Fabricas_Number.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Fabricas_Number.Medicamentos_Id" asp-items="Model.FabList" class="form-select border shadow">
                        <option disabled selected> --Select a Medicamento--</option>
                    </select>
                    <label asp-for="Fabricas_Number.Medicamentos_Id" class="ms-2"></label>
                    <span asp-validation-for="Fabricas_Number.Medicamentos_Id" class="text-danger"></span>
                </div>
                <input asp-for="Fabricas_Number.Id" hidden />
                <div class="form-floating py-2 col-12">
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Fabricas_Number.Id" class="form-control border shadow" />
                        <label asp-for="Fabricas_Number.Id" class="ms-2"></label>
                        <span asp-validation-for="Fabricas_Number.Id" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Fabricas_Number.Local" class="form-control border shadow" />
                        <label asp-for="Fabricas_Number.Local" class="ms-2"></label>
                        <span asp-validation-for="Fabricas_Number.Local" class="text-danger"></span>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i>
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Farmacia.Web/Views/Farm/Create.cshtml
@model Farmacia.Domain.Entities.Medicamentos
@using Farmacia.Domain.Entities
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create a Medicines</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            
            <div class="form-floating py-1 col-12">
                <input asp-for="@Model.Name" class="form-control border shadow" />
                <label asp-for="Name" class="ms-2"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                <input asp-for="@Model.Description" class="form-control border shadow" />
                <label asp-for="Description" class="ms-2"></label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                <input asp-for="@Model.Amount" class="form-control border shadow" />
                <label asp-for="Amount" class="ms-2"></label>
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                <input asp-for="@Model.ImageUrl" class="form-control border shadow" />
                <label asp-for="ImageUrl" class="ms-2"></label>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i>Submit
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i>
                        Cancel
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Farmacia.Web/Views/Farm/Delete.cshtml
@model Farmacia.Domain.Entities.Medicamentos
@using Farmacia.Domain.Entities
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete a Medicine</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">

        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="form-floating py-2 col-12">
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Amount" class="form-control border shadow" />
                    <label asp-for="Amount" class="ms-2"></label>
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.ImageUrl" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-trash-fill"></i>
                            Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Farmacia.Web/Views/Farm/Index.cshtml
@model IEnumerable<Farmacia.Domain.Entities.Medicamentos>    

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-0">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="table table-bordered table-striped">Medicines List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3 ">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Farm" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i>Create a New Medicine
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Amount</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Id</td>
                        <td>@obj.Name</td>
                        <td>@obj.Description</td>
                        <td>@obj.Price</td>
                        <td>@obj.Amount</td>
                        <td>@obj.ImageUrl</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-action="Update" asp-route-farmId="@obj.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-action="Delete" asp-route-farmId="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Farmacia.Web/Views/Farm/Update.cshtml
@model Farmacia.Domain.Entities.Medicamentos
@using Farmacia.Domain.Entities
    <div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update a Medicine</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">

        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="form-floating py-2 col-12">
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.Amount" class="form-control border shadow" />
                    <label asp-for="Amount" class="ms-2"></label>
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.ImageUrl" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i>
                            Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Farmacia.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Farmacia.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Farmacia.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Farmacia.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Farmacia.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="">Farmacia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fabrica" asp-action="">Fabrica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Made with <i class="bg-info bi-heart-fill"></i> by Andre  Morais
        </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Farmacia.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "progressBar": true,
            "positionClass": "toast-top-center"
        }
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "progressBar": true,
            "positionClass": "toast-top-center"
        }
        toastr.success('@TempData["success"]');
    </script>
}